<a href="https://colab.research.google.com/github/Siddhant2307/ideal-giggle/blob/master/imgprohect.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:

from keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt


(trainX,trainy),(testX,testy)=fashion_mnist.load_data()
def load_dataset():
  (trainX,trainy),(testX,testy)=fashion_mnist.load_data()
  trainX=trainX.reshape((trainX.shape[0],28,28,1))
  testX=testX.reshape((testX.shape[0],28,28,1))
  trainy=to_categorical(trainy)
  testy=to_categorical(testy)
  return trainX,trainy,testX,testy
np.unique(trainy)

seed=2
from sklearn.model_selection import StratifiedShuffleSplit
data_split=StratifiedShuffleSplit(test_size=0.75,random_state=seed)
for train_index,test_index in data_split.split(trainX,trainy):
    split_data_65,split_data_35=trainX[train_index],trainX[test_index]
    split_label_65,split_label_35=trainy[train_index],trainy[test_index]
train_test_split=StratifiedShuffleSplit(test_size=0.3,random_state=seed)
for train_index,test_index in train_test_split.split(split_data_65,split_label_65):
    train_data_70,test_data_30=split_data_65[train_index],split_data_65[test_index]
    train_label_70,test_label_30=split_label_65[train_index],split_label_65[test_index]
train_data=train_data_70
train_label=train_label_70
test_data=test_data_30
test_label=test_label_30
print("train data :",train_data.shape)
print("train label : ",train_label.shape)
print("test data :",test_data.shape)    
print("test label : ",test_label.shape)
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']


train_data=train_data.astype('float64')/255.0
test_data=test_data.astype('float64')/255.0

train_data_flat=train_data.reshape(train_data.shape[0],-1)
test_data_flat=test_data.reshape(test_data.shape[0],-1)
print("train data flat :",train_data_flat.shape)
print("test data flat :",test_data_flat.shape)
train_data_flat_t=train_data_flat
test_data_flat_t=test_data_flat
train_data_flat_t=train_data_flat
test_data_flat_t=test_data_flat

train data : (10500, 28, 28)
train label :  (10500,)
test data : (4500, 28, 28)
test label :  (4500,)
train data flat : (10500, 784)
test data flat : (4500, 784)


In [4]:
from sklearn.decomposition import PCA
train_data_pca=PCA(n_components=min(train_data.shape)).fit_transform(train_data_flat)
test_data_pca=PCA(n_components=min(test_data.shape)).fit_transform(test_data_flat)
print(train_data_pca.shape)
print(test_data_pca.shape)


(10500, 28)
(4500, 28)


In [5]:
from skimage import color
def svdFeatures(input_data):
  svdArray_input_data=[]
  size=input_data.shape[0]
  for i in range(0,size):
    U,s,V=np.linalg.svd(input_data[i],full_matrices=False)
    S=[s[i] for i in range(28)]
    svdArray_input_data.append(S)
    svdMatrix_input_data=np.matrix(svdArray_input_data)
  return svdMatrix_input_data

train_data_svd=svdFeatures(train_data)
test_data_svd=svdFeatures(test_data)
print(train_data_svd.shape)
print(test_data_svd.shape)

(10500, 28)
(4500, 28)


In [25]:

from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
clf=SVC(kernel='linear',gamma=0.001, probability =True , random_state=0)
clf.fit(train_data_flat_t,train_label)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='linear',
    max_iter=-1, probability=True, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [26]:
predict1=clf.predict(test_data_flat_t)

In [27]:
score=clf.score(test_data_flat_t,test_label)
print('score:',score)
conf_matrix=confusion_matrix(test_label,predict1)
print('Confusion matrix : ',conf_matrix)


score: 0.8291111111111111
Confusion matrix :  [[369   1   9  23   1   0  41   0   6   0]
 [  3 431   3   8   1   0   3   0   0   1]
 [  6   0 337   8  60   0  39   0   0   0]
 [ 34  11   5 373  12   0  15   0   0   0]
 [  7   0  50  17 334   0  41   0   1   0]
 [  1   0   0   0   0 422   0  16   2   9]
 [ 72   2  74  13  51   0 228   0  10   0]
 [  0   0   0   0   0  18   0 415   0  17]
 [  5   1   9   7   3   5   8   3 409   0]
 [  1   0   0   0   0  16   0  19   1 413]]


In [28]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
clf2=SVC(kernel='linear',gamma=0.001, probability =True , random_state=0)
clf2.fit(train_data_pca,train_label)
predict2=clf2.predict(test_data_pca)
score2=clf2.score(test_data_pca,test_label)
print('score:',score2)
conf_matrix2=confusion_matrix(test_label,predict2)
print('Confusion matrix : ',conf_matrix2)

score: 0.5704444444444444
Confusion matrix :  [[329  11   4  28   0   1  70   0   7   0]
 [ 17 356   5  62   3   1   6   0   0   0]
 [ 24  23 252   6  50   1  82   0  12   0]
 [ 59 232   5 105  20   2  26   0   1   0]
 [  6   9 103  18 190   0 119   0   5   0]
 [ 14   0   0   0   0 274   0  86  26  50]
 [ 69   6  79  18  90   4 161   0  23   0]
 [  0   0   0   0   0  42   0 276 106  26]
 [  1   1  10  10  12  74  27   0 298  17]
 [ 16   0   0   1   1  39   2  37  28 326]]


In [30]:
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
clf3=SVC(kernel='linear',gamma=0.001, probability =True , random_state=0)
clf3.fit(train_data_svd,train_label)
predict3=clf3.predict(test_data_svd)
score3=clf3.score(test_data_svd,test_label)
print('score:',score3)
conf_matrix3=confusion_matrix(test_label,predict3)
print('Confusion matrix : ',conf_matrix3)

score: 0.5782222222222222
Confusion matrix :  [[205  10  22  44  44  24  32  14  20  35]
 [  4 368   3  44   2  10   0  15   2   2]
 [ 35   5 203  19  66  25  56   9  25   7]
 [ 30  93  20 183  13  20   8  60  18   5]
 [ 40   4  94  39 177  21  47   4  17   7]
 [  3  14   0   3   2 351   8  59   3   7]
 [ 61   3  83  33  52  40 113   8  45  12]
 [  7  15   0  19   1  52   3 300   3  50]
 [  6   4   3  19   9  13  24  20 352   0]
 [ 45   1   0   3   2  10   8  30   1 350]]
