<a href="https://colab.research.google.com/github/Siddhant2307/ideal-giggle/blob/master/imgproject_MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt


(trainX,trainy),(testX,testy)=fashion_mnist.load_data()
def load_dataset():
  (trainX,trainy),(testX,testy)=fashion_mnist.load_data()
  trainX=trainX.reshape((trainX.shape[0],28,28,1))
  testX=testX.reshape((testX.shape[0],28,28,1))
  trainy=to_categorical(trainy)
  testy=to_categorical(testy)
  return trainX,trainy,testX,testy
np.unique(trainy)

seed=2
from sklearn.model_selection import StratifiedShuffleSplit
data_split=StratifiedShuffleSplit(test_size=0.75,random_state=seed)
for train_index,test_index in data_split.split(trainX,trainy):
    split_data_65,split_data_35=trainX[train_index],trainX[test_index]
    split_label_65,split_label_35=trainy[train_index],trainy[test_index]
train_test_split=StratifiedShuffleSplit(test_size=0.3,random_state=seed)
for train_index,test_index in train_test_split.split(split_data_65,split_label_65):
    train_data_70,test_data_30=split_data_65[train_index],split_data_65[test_index]
    train_label_70,test_label_30=split_label_65[train_index],split_label_65[test_index]
train_data=train_data_70
train_label=train_label_70
test_data=test_data_30
test_label=test_label_30
print("train data :",train_data.shape)
print("train label : ",train_label.shape)
print("test data :",test_data.shape)    
print("test label : ",test_label.shape)
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']


train_data=train_data.astype('float64')/255.0
test_data=test_data.astype('float64')/255.0

train_data_flat=train_data.reshape(train_data.shape[0],-1)
test_data_flat=test_data.reshape(test_data.shape[0],-1)
print("train data flat :",train_data_flat.shape)
print("test data flat :",test_data_flat.shape)
train_data_flat_t=train_data_flat
test_data_flat_t=test_data_flat
train_data_flat_t=train_data_flat
test_data_flat_t=test_data_flat

4431872/4422102 [==============================] - 0s 0us/step
train data : (10500, 28, 28)
train label :  (10500,)
test data : (4500, 28, 28)
test label :  (4500,)
train data flat : (10500, 784)
test data flat : (4500, 784)


In [2]:
from sklearn.decomposition import PCA
train_data_pca=PCA(n_components=min(train_data.shape)).fit_transform(train_data_flat)
test_data_pca=PCA(n_components=min(test_data.shape)).fit_transform(test_data_flat)
print(train_data_pca.shape)
print(test_data_pca.shape)

(10500, 28)
(4500, 28)


In [3]:
from skimage import color
def svdFeatures(input_data):
  svdArray_input_data=[]
  size=input_data.shape[0]
  for i in range(0,size):
    U,s,V=np.linalg.svd(input_data[i],full_matrices=False)
    S=[s[i] for i in range(28)]
    svdArray_input_data.append(S)
    svdMatrix_input_data=np.matrix(svdArray_input_data)
  return svdMatrix_input_data

train_data_svd=svdFeatures(train_data)
test_data_svd=svdFeatures(test_data)
print(train_data_svd.shape)
print(test_data_svd.shape)

(10500, 28)
(4500, 28)


In [6]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
MLP1=MLPClassifier()
MLP1.fit(train_data_flat_t,train_label)

mlp_predict1 = MLP1.predict(test_data_flat_t)
score1 = MLP1.score(test_data_flat_t,test_label)
print("score", score1)

Confusion_Matrix1 = metrics.confusion_matrix(test_label, mlp_predict1)
print("Confusion Matrix",Confusion_Matrix1)

score 0.8686666666666667
Confusion Matrix [[387   1  11  13   1   0  31   0   6   0]
 [  1 433   1   9   3   0   3   0   0   0]
 [  6   2 369   5  42   1  24   0   1   0]
 [ 20  11   3 398  12   0   6   0   0   0]
 [  4   2  32  24 359   0  27   0   2   0]
 [  0   0   0   0   0 424   0  16   3   7]
 [ 66   2  47  15  41   0 271   0   8   0]
 [  0   0   0   0   0  11   0 423   1  15]
 [  2   1   5   6   2   3   5   3 423   0]
 [  0   0   0   0   0   8   0  18   2 422]]


In [8]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
MLP2=MLPClassifier()
MLP2.fit(train_data_pca,train_label)

mlp_predict2 = MLP2.predict(test_data_pca)
score2 = MLP2.score(test_data_pca,test_label)
print("score", score2)

Confusion_Matrix2 = metrics.confusion_matrix(test_label, mlp_predict2)
print("Confusion Matrix",Confusion_Matrix2)

score 0.4653333333333333
Confusion Matrix [[279  11   9  64   2   2  78   1   4   0]
 [ 10 278  28 115   2   1  16   0   0   0]
 [ 20  35 119   2  94   5 139   0  36   0]
 [ 33 190  36 118  43   8  16   1   4   1]
 [  5   7 113   8 165   1 145   0   6   0]
 [  7   0   0   0   0 332   2  61  21  27]
 [ 74   5  51  28 105  14 158   1  13   1]
 [  0   0   0   0   0  59   0 171 198  22]
 [ 10   0  15   1   7  53  46   4 204 110]
 [  4   0   0   4   3  20  10 107  32 270]]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [9]:
from sklearn.neural_network import MLPClassifier
from sklearn import metrics
MLP3=MLPClassifier()
MLP3.fit(train_data_svd,train_label)

mlp_predict3 = MLP3.predict(test_data_svd)
score3 = MLP3.score(test_data_svd,test_label)
print("score", score3)

Confusion_Matrix3 = metrics.confusion_matrix(test_label, mlp_predict3)
print("Confusion Matrix",Confusion_Matrix3)

score 0.6355555555555555
Confusion Matrix [[231   0  29  40  41   3  46   6  27  27]
 [  3 357   0  59   3   8   2  15   0   3]
 [ 44   0 177  11 102   4  75   1  29   7]
 [ 17  48   9 258  20  14   6  56  14   8]
 [ 27   3  52  35 233   8  57   5  21   9]
 [  0   4   0   5   3 359   4  63   6   6]
 [ 51   0  42  31  79  14 167   1  45  20]
 [  0   2   0  15   3  46   2 330   2  50]
 [  6   2   4  15   9   8  20  12 374   0]
 [ 27   1   1   2   4  11   4  24   2 374]]


/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
