<a href="https://colab.research.google.com/github/Siddhant2307/ideal-giggle/blob/master/imgprojectNBC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from keras.datasets import fashion_mnist
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt


(trainX,trainy),(testX,testy)=fashion_mnist.load_data()
def load_dataset():
  (trainX,trainy),(testX,testy)=fashion_mnist.load_data()
  trainX=trainX.reshape((trainX.shape[0],28,28,1))
  testX=testX.reshape((testX.shape[0],28,28,1))
  trainy=to_categorical(trainy)
  testy=to_categorical(testy)
  return trainX,trainy,testX,testy
np.unique(trainy)

seed=2
from sklearn.model_selection import StratifiedShuffleSplit
data_split=StratifiedShuffleSplit(test_size=0.75,random_state=seed)
for train_index,test_index in data_split.split(trainX,trainy):
    split_data_65,split_data_35=trainX[train_index],trainX[test_index]
    split_label_65,split_label_35=trainy[train_index],trainy[test_index]
train_test_split=StratifiedShuffleSplit(test_size=0.3,random_state=seed)
for train_index,test_index in train_test_split.split(split_data_65,split_label_65):
    train_data_70,test_data_30=split_data_65[train_index],split_data_65[test_index]
    train_label_70,test_label_30=split_label_65[train_index],split_label_65[test_index]
train_data=train_data_70
train_label=train_label_70
test_data=test_data_30
test_label=test_label_30
print("train data :",train_data.shape)
print("train label : ",train_label.shape)
print("test data :",test_data.shape)    
print("test label : ",test_label.shape)
class_names=['T-shirt/top','Trouser','Pullover','Dress','Coat','Sandal','Shirt','Sneaker','Bag','Ankle boot']


train_data=train_data.astype('float64')/255.0
test_data=test_data.astype('float64')/255.0

train_data_flat=train_data.reshape(train_data.shape[0],-1)
test_data_flat=test_data.reshape(test_data.shape[0],-1)
print("train data flat :",train_data_flat.shape)
print("test data flat :",test_data_flat.shape)
train_data_flat_t=train_data_flat
test_data_flat_t=test_data_flat
train_data_flat_t=train_data_flat
test_data_flat_t=test_data_flat

4431872/4422102 [==============================] - 0s 0us/step
train data : (10500, 28, 28)
train label :  (10500,)
test data : (4500, 28, 28)
test label :  (4500,)
train data flat : (10500, 784)
test data flat : (4500, 784)


In [2]:
from sklearn.decomposition import PCA
train_data_pca=PCA(n_components=min(train_data.shape)).fit_transform(train_data_flat)
test_data_pca=PCA(n_components=min(test_data.shape)).fit_transform(test_data_flat)
print(train_data_pca.shape)
print(test_data_pca.shape)

(10500, 28)
(4500, 28)


In [3]:
from skimage import color
def svdFeatures(input_data):
  svdArray_input_data=[]
  size=input_data.shape[0]
  for i in range(0,size):
    U,s,V=np.linalg.svd(input_data[i],full_matrices=False)
    S=[s[i] for i in range(28)]
    svdArray_input_data.append(S)
    svdMatrix_input_data=np.matrix(svdArray_input_data)
  return svdMatrix_input_data

train_data_svd=svdFeatures(train_data)
test_data_svd=svdFeatures(test_data)
print(train_data_svd.shape)
print(test_data_svd.shape)

(10500, 28)
(4500, 28)


In [4]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
gnb1 = GaussianNB()
train = gnb1.fit(train_data_flat_t, train_label)


y_pred1 = gnb1.predict(test_data_flat_t)
score1 = gnb1.score(test_data_flat_t, test_label)
print("score", score1)

Confusion_Matrix1 = metrics.confusion_matrix(test_label, y_pred1)
print("Confusion Matrix",Confusion_Matrix1)

score 0.5624444444444444
Confusion Matrix [[251  43  18  94  20   0   7   0  17   0]
 [  1 431   4   9   1   0   4   0   0   0]
 [  0  14 202  35 180   0  14   0   5   0]
 [  1 291   2 150   3   0   2   0   1   0]
 [  2  27  37  71 308   0   3   0   2   0]
 [  0   0   1   0   0 126   0 310   4   9]
 [ 36  38  63 108 160   0  18   0  27   0]
 [  0   0   0   0   0   2   0 442   0   6]
 [  1   5  28  37  42   3   7   1 326   0]
 [  0   0   0   0   0  11   4 154   4 277]]


In [5]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
gnb2 = GaussianNB()
train = gnb2.fit(train_data_pca, train_label)


y_pred2 = gnb2.predict(test_data_pca)
score2 = gnb2.score(test_data_pca, test_label)
print("score", score2)

Confusion_Matrix2 = metrics.confusion_matrix(test_label, y_pred2)
print("Confusion Matrix",Confusion_Matrix2)

score 0.6275555555555555
Confusion Matrix [[352   0   8  30   1   5  42   0  12   0]
 [ 14 305  37  48   4  11   8   0  23   0]
 [  1   0 255   4  55  12  94   0  29   0]
 [ 75  18   2 260  14   9  32   0  40   0]
 [  7   0 106  27 245   3  55   0   7   0]
 [  1   0   1   1   0 304   1  78  31  33]
 [ 86   0  65  11 109  13 152   0  14   0]
 [  0   0   0   0   1 146   4 214  39  46]
 [  0   0  24   7   8  21  15  27 346   2]
 [  0   0   0   0   1  19   2  16  21 391]]


In [6]:
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
gnb3 = GaussianNB()
train = gnb3.fit(train_data_svd, train_label)


y_pred3 = gnb3.predict(test_data_svd)
score3 = gnb3.score(test_data_svd, test_label)
print("score", score3)

Confusion_Matrix3 = metrics.confusion_matrix(test_label, y_pred3)
print("Confusion Matrix",Confusion_Matrix3)

score 0.296
Confusion Matrix [[ 47 103  20  54  44   8   8 122   2  42]
 [  0 422   1   0   3   1   1  19   0   3]
 [ 17  97  48  36  75   0   8 132   7  30]
 [  1 312   1   1   3   2   0 119   0  11]
 [ 10  61  32  12 142   7   3 129   5  49]
 [  3 127   0   0   1  69   1 168   2  79]
 [ 24  58  29  18  85  19  15 122  14  66]
 [  0 161   0   0   0   2   0 267   0  20]
 [ 10  68  14  17  37  23   9 107  70  95]
 [  5   1   0   0  11  19   5 158   0 251]]
